name: realworld_flutter
description: A Realworld Flutter Application

version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.16.0
  bloc: ^0.15.0
  flutter_bloc: ^0.21.0

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  fonts:
    - family: MerriweatherSans
      fonts:
        - asset: fonts/MerriweatherSans-regular.ttf
        - asset: fonts/MerriweatherSans-italic.ttf
          style: italic
        - asset: fonts/MerriweatherSans-800.ttf
          weight: 800
        - asset: fonts/MerriweatherSans-800italic.ttf
          style: italic
          weight: 800
        - asset: fonts/MerriweatherSans-700.ttf
          weight: 700
        - asset: fonts/MerriweatherSans-700italic.ttf
          style: italic
          weight: 700
        - asset: fonts/MerriweatherSans-300.ttf
          weight: 300
        - asset: fonts/MerriweatherSans-300italic.ttf
          style: italic
          weight: 300
    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-regular.ttf
        - asset: fonts/SourceSansPro-italic.ttf
          style: italic
        - asset: fonts/SourceSansPro-900.ttf
          weight: 900
        - asset: fonts/SourceSansPro-900italic.ttf
          style: italic
          weight: 900
        - asset: fonts/SourceSansPro-700.ttf
          weight: 700
        - asset: fonts/SourceSansPro-700italic.ttf
          style: italic
          weight: 700
        - asset: fonts/SourceSansPro-600.ttf
          weight: 600
        - asset: fonts/SourceSansPro-600italic.ttf
          style: italic
          weight: 600
        - asset: fonts/SourceSansPro-300.ttf
          weight: 300
        - asset: fonts/SourceSansPro-300italic.ttf
          style: italic
          weight: 300
        - asset: fonts/SourceSansPro-200.ttf
          weight: 200
        - asset: fonts/SourceSansPro-200italic.ttf
          style: italic
          weight: 200
    - family: SourceSerifPro
      fonts:
        - asset: fonts/SourceSerifPro-regular.ttf
        - asset: fonts/SourceSerifPro-700.ttf
          weight: 700
        - asset: fonts/SourceSerifPro-600.ttf
          weight: 600
    - family: TitilliumWeb
      fonts:
        - asset: fonts/TitilliumWeb-regular.ttf
        - asset: fonts/TitilliumWeb-italic.ttf
          style: italic
        - asset: fonts/TitilliumWeb-900.ttf
          weight: 900
        - asset: fonts/TitilliumWeb-700.ttf
          weight: 700
        - asset: fonts/TitilliumWeb-700italic.ttf
          style: italic
          weight: 700
        - asset: fonts/TitilliumWeb-600.ttf
          weight: 600
        - asset: fonts/TitilliumWeb-600italic.ttf
          style: italic
          weight: 600
        - asset: fonts/TitilliumWeb-300.ttf
          weight: 300
        - asset: fonts/TitilliumWeb-300italic.ttf
          style: italic
          weight: 300
        - asset: fonts/TitilliumWeb-200.ttf
          weight: 200
        - asset: fonts/TitilliumWeb-200italic.ttf
          style: italic
          weight: 200
